spring:
  datasource:
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    username: root # mysql用户名
    password: 123456 # mysql登陆密码
    url: jdbc:mysql://localhost:3306/ssmbuild?serverTimezone=Asia/Shanghai
    # 使用 druid 数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
      # 注意以下不能有空格，路径必须连续
#      - classpath:schema.sql
# 注意，只需要第一次创建表和插入数据，第二次就应该把配置注释掉和把数据库脚本文件删掉

    # 配置初始化大小、最小、最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 3000
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    poolPreparedStatements: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    # 配置web监控,默认配置也和下面相同(除用户名密码，enabled默认false外)，其他可以不配
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


