dubbo:
  application:
    name: order-service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20882
  monitor:
    protocol: registry
server:
  port: 8082
