spring:
  datasource:
    url: jdbc:mysql://134.175.115.74:3307/ssmbuild?serverTimezone=Asia/Shanghai
    username: root
    password: 2019ruanjiankeshe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    # 数据表的生成策略：更新或创建数据表（只要实体类一改动）
      ddl-auto: update
    # 每次增删改查时显示SQL
    show-sql: true
